name: dev
on: [push]
jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node Js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

  server:
    needs: set-up
    runs-on: ubuntu-latest
    steps:
      - name: Linting
        working-directory: server
        run: pnpm run lint

      - name: Unit Test
        working-directory: server
        run: pnpm run test

      - name: End to end Test
        working-directory: server
        run: pnpm run test:e2e

  client:
    needs: set-up
    runs-on: ubuntu-latest
    steps:
      - name: Linting
        working-directory: client
        run: pnpm run lint
