name: dev
on:
  pull_request:
    branches: main
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: setup node env
        uses: ./utils/setup-node.yml

      - name: Install Dependencies
        working-directory: server
        run: pnpm install

      - name: Linting
        working-directory: server
        run: pnpm run lint

      - name: Unit Test
        working-directory: server
        run: pnpm run test

      - name: End to end Test
        working-directory: server
        run: pnpm run test:e2e

  client:
    runs-on: ubuntu-latest
    steps:
      - name: setup node env
        uses: ./utils/setup-node.yml

      - name: Install Dependencies
        working-directory: client
        run: pnpm install

      - name: Linting
        working-directory: client
        run: pnpm run lint
